/**
 * Created by 薛凯韬 on 2016/11/2.
 */
export const DELETE_CANDIDATE_BEGIN = 'DELETE_CANDIDATE_BEGIN';
export const DELETE_CANDIDATE_SUCCESS = 'DELETE_CANDIDATE_SUCCESS';
export const DELETE_CANDIDATE_ERROR = 'DELETE_CANDIDATE_ERROR';
export const LOAD_ALL_CANDIDATE_SUCCESS = 'LOAD_ALL_CANDIDATE_SUCCESS';
export const LOAD_ALL_CANDIDATE_ERROR = 'LOAD_ALL_CANDIDATE_ERROR';
export const LOAD_ALL_CANDIDATE_BEGIN = 'LOAD_ALL_CANDIDATE_BEGIN';
