export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const LOAD_ALL_ROOM_SUCCESS = 'LOAD_ALL_ROOM_SUCCESS';
