export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const DELETE_ROOM = 'DELETE_ROOM';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_ERROR = 'DELETE_ROOM_ERROR';
export const LOAD_ALL_ROOMS_SUCCESS = 'LOAD_ALL_ROOMS_SUCCESS';
export const LOAD_ALL_ROOMS_ERROR = 'LOAD_ALL_ROOMS_ERROR';
export const LOAD_ALL_ROOMS = 'LOAD_ALL_ROOMS';
export const MODIFY_ROOM = 'MODIFY_ROOM';
export const MODIFY_ROOM_SUCCESS = 'MODIFY_ROOM_SUCCESS';
export const MODIFY_ROOM_ERROR = 'MODIFY_ROOM_ERROR';
export const ADD_ROOM = 'ADD_ROOM';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_ERROR = 'ADD_ROOM_ERROR';
export const UPLOAD_IMAGE = 'UPLOAD_FILE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';

export const ADD_PROBLEM = 'ADD_PROBLEM';
export const ADD_CHOICE_PROBLEM_SUCCESS = 'ADD_CHOICE_PROBLEM_SUCCESS';
export const ADD_PROBLEM_ERROR = 'ADD_PROBLEM_ERROR';
export const EDIT_PROBLEM = 'EDIT_PROBLEM';
export const EDIT_PROBLEM_ERROR = 'EDIT_PROBLEM_ERROR';

export const LOAD_ROOM_SUCCESS = 'LOAD_ROOM_SUCCESS';
export const LOAD_ROOM_ERROR = 'LOAD_ROOM_ERROR';
export const LOAD_ROOM = 'LOAD_ROOM';
export const LOAD_ALL_PROBLEMS_SUCCESS = 'LOAD_ALL_PROBLEMS_SUCCESS';
export const LOAD_ALL_PROBLEMS_ERROR = 'LOAD_ALL_PROBLEMS_ERROR';
export const LOAD_ALL_PROBLEMS = 'LOAD_ALL_PROBLEMS';
export const DELETE_PROBLEM_SUCCESS = 'DELETE_PROBLEM_SUCCESS';
export const DELETE_PROBLEM_ERROR = 'DELETE_PROBLEM_ERROR';
export const DELETE_PROBLEM = 'DELETE_PROBLEM';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';

export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const DELETE_CANDIDATE_BEGIN = 'DELETE_CANDIDATE_BEGIN';
export const DELETE_CANDIDATE_SUCCESS = 'DELETE_CANDIDATE_SUCCESS';
export const DELETE_CANDIDATE_ERROR = 'DELETE_CANDIDATE_ERROR';
export const EDIT_CANDIDATE_BEGIN = 'EDIT_CANDIDATE_BEGIN';
export const EDIT_CANDIDATE_SUCCESS = 'EDIT_CANDIDATE_SUCCESS';
export const EDIT_CANDIDATE_ERROR = 'EDIT_CANDIDATE_ERROR';
export const LOAD_ALL_CANDIDATE_SUCCESS = 'LOAD_ALL_CANDIDATE_SUCCESS';
export const LOAD_ALL_CANDIDATE_ERROR = 'LOAD_ALL_CANDIDATE_ERROR';
export const LOAD_ALL_CANDIDATE_BEGIN = 'LOAD_ALL_CANDIDATE_BEGIN';
export const ADD_CANDIDATE_SUCCESS = 'ADD_CANDIDATE_SUCCESS';
export const ADD_CANDIDATE_ERROR = 'ADD_CANDIDATE_ERROR';
export const ADD_CANDIDATE_BEGIN = 'ADD_CANDIDATE_BEGIN';
export const LIST_CANDIDATE_SUCCESS = 'LIST_CANDIDATE_SUCCESS';
export const LIST_CANDIDATE_ERROR = 'LIST_CANDIDATE_ERROR';
export const LIST_CANDIDATE_BEGIN = 'LIST_CANDIDATE_BEGIN';
